services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_PASSWORD: "local_password"
    ports:
      # A MÁGICA: expor a porta 5432 do container para a máquina host
      - "5432:5432"
